#include "ui/style/ui.inc"

#define RenderInformations() \
        InformationWindow; \
		InformationTitle( 0, 0, "Gamemode" ); \
		InformationTitle( 0, 1, "Credits" ); \
		InformationTitle( 1, 0, "Commands" ); \
		InformationTitle( 1, 1, "Changelog" ); \
        InformationDescription( 0, 0, "A Modded Version of the loved Gamemode Infected, where Bounces \nare Possibile and the only defense against the Infected is \na good old Shotgun :D" ); \
        InformationDescription( 0, 1, "urLiver\nClaudi0\nZECxR3ap3r\nWiizard\nJoelrau\nUwUneedsBunni\nLastDemon99" ); \
        InformationDescriptionSplit( 0, 1, "M0vx\nSully\nClippy\nClickerz\nTMGlion\nSloth\nRevox" ); \
        InformationDescription( 1, 0, "Chat Commands \nPromote with: ?prestige \n\nBinds \n[{+actionslot 6}] = Suicide \n[{vote no}] = Toggle Fullbright \n[{vote yes}] = Toggle Render Distance \n" ); \
        InformationDescription( 1, 1, "V1.0 Initiale Release" );




